/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Formularios;

import conection.Consultas;
import conection.Metodos;
import conection.Metodos.ForeignKeyConstraintException;

import javax.swing.JOptionPane;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author luill
 */
public class frmFormularioCiudad extends javax.swing.JDialog {

    /**
     * Creates new form frmFormulario
     */
    public frmFormularioCiudad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtNumCiudad = new javax.swing.JTextField();
        TxtCiudad = new javax.swing.JTextField();
        NewRegistro = new javax.swing.JButton();
        DeleteRegistro = new javax.swing.JButton();
        UpdateRegistro = new javax.swing.JButton();
        SelecRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonvolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaImpresiones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        TxtCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCiudadActionPerformed(evt);
            }
        });

        NewRegistro.setText("Nuevo Registro");
        NewRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewRegistroActionPerformed(evt);
            }
        });

        DeleteRegistro.setText("Eliminar Registro");
        DeleteRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRegistroActionPerformed(evt);
            }
        });

        UpdateRegistro.setText("Actualizar Registro");
        UpdateRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRegistroActionPerformed(evt);
            }
        });

        SelecRegistro.setText("Consultar Datos");
        SelecRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecRegistroActionPerformed(evt);
            }
        });

        jLabel1.setText("número de ciudad");

        jLabel2.setText("nombre de la ciudad");

        botonvolver.setText("Volver");
        botonvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonvolverActionPerformed(evt);
            }
        });

        TablaImpresiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id_ciudad", "nombre_ciudad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaImpresiones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NewRegistro)
                                .addGap(45, 45, 45)
                                .addComponent(DeleteRegistro)
                                .addGap(55, 55, 55)
                                .addComponent(UpdateRegistro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addComponent(SelecRegistro))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtNumCiudad)
                                .addComponent(TxtCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(botonvolver)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewRegistro)
                    .addComponent(DeleteRegistro)
                    .addComponent(UpdateRegistro)
                    .addComponent(SelecRegistro))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TxtNumCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)
                        .addComponent(TxtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230)
                        .addComponent(botonvolver))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCiudadActionPerformed

    private void NewRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewRegistroActionPerformed
        String idCiudad = TxtNumCiudad.getText().trim();
    String nombreCiudad = TxtCiudad.getText().trim();
    
    // Verificar si ambos campos no están vacíos
    if (!idCiudad.isEmpty() && !nombreCiudad.isEmpty()) {
        try {
            // Convertir el idCiudad a entero
            int id = Integer.parseInt(idCiudad);
            
            // Llamar al método insertarCiudad con los datos proporcionados
            Consultas consultas = new Consultas();
            consultas.insertarCiudad(nombreCiudad, id);
            
            // Limpiar los campos de texto después de insertar la ciudad
            TxtNumCiudad.setText("");
            TxtCiudad.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de la ciudad debe ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese tanto el ID como el nombre de la ciudad.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
    } // TODO add your handling code here:
    }//GEN-LAST:event_NewRegistroActionPerformed

    private void DeleteRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRegistroActionPerformed

String idCiudad = TxtNumCiudad.getText().trim();

    // Verificar si el campo de ID no está vacío
    if (!idCiudad.isEmpty()) {
        try {
            // Convertir el idCiudad a entero
            int id = Integer.parseInt(idCiudad);

            // Llamar al método borrarCiudad con el ID proporcionado
            Consultas consultas = new Consultas();
            consultas.borrarCiudad(id);

            // Limpiar el campo de ID después de borrar la ciudad
            TxtNumCiudad.setText("");
            JOptionPane.showMessageDialog(this, "Registro borrado con éxito de la tabla ciudad.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de la ciudad debe ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Metodos.ForeignKeyConstraintException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar borrar la ciudad: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese el ID de la ciudad que desea borrar.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
    }
// TODO add your handling code here:
    }//GEN-LAST:event_DeleteRegistroActionPerformed

    private void UpdateRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRegistroActionPerformed
        String idCiudad = TxtNumCiudad.getText().trim();
    String nuevoNombreCiudad = TxtCiudad.getText().trim();
    
    // Verificar si ambos campos no están vacíos
    if (!idCiudad.isEmpty() && !nuevoNombreCiudad.isEmpty()) {
        try {
            // Convertir el idCiudad a entero
            int id = Integer.parseInt(idCiudad);
            
            // Llamar al método actualizarCiudad con los datos proporcionados
            Consultas consultas = new Consultas();
            consultas.actualizarCiudad(id, nuevoNombreCiudad);
            
            // Limpiar los campos de texto después de actualizar la ciudad
            TxtNumCiudad.setText("");
            TxtCiudad.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de la ciudad debe ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese tanto el ID como el nuevo nombre de la ciudad.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
    } // TODO add your handling code here:
    }//GEN-LAST:event_UpdateRegistroActionPerformed

    private void SelecRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecRegistroActionPerformed
        Consultas consultas = new Consultas();
    ResultSet rs = consultas.consultarTodasLasCiudades();
    
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID Ciudad");
    modelo.addColumn("Nombre Ciudad");
    
    // Verificar si se obtuvieron resultados
    if (rs != null) {
        try {
            // Limpiar el modelo antes de agregar nuevos datos
            modelo.setRowCount(0);
            
            // Iterar sobre los resultados del ResultSet y agregarlos al modelo
            while (rs.next()) {
                int idCiudad = rs.getInt("id_ciudad");
                String nombreCiudad = rs.getString("nombre_ciudad");
                modelo.addRow(new Object[]{idCiudad, nombreCiudad});
            }
            
            // Establecer el modelo en la tabla
            TablaImpresiones.setModel(modelo);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al procesar los resultados de la consulta: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "No se encontraron resultados.", "Información", JOptionPane.INFORMATION_MESSAGE);
    } 
    }//GEN-LAST:event_SelecRegistroActionPerformed

    private void botonvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonvolverActionPerformed
                                         
    frmPrincipal principal = new frmPrincipal(null, true);
    // Hacer visible la instancia de frmPrincipal
    principal.setVisible(true);
    // Cerrar el formulario actual
    dispose(); // Cierra el formulario actual
// TODO add your handling code here:
    }//GEN-LAST:event_botonvolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFormularioCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFormularioCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFormularioCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFormularioCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmFormularioCiudad dialog = new frmFormularioCiudad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteRegistro;
    private javax.swing.JButton NewRegistro;
    private javax.swing.JButton SelecRegistro;
    private javax.swing.JTable TablaImpresiones;
    private javax.swing.JTextField TxtCiudad;
    private javax.swing.JTextField TxtNumCiudad;
    private javax.swing.JButton UpdateRegistro;
    private javax.swing.JButton botonvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
