/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Formularios;
import java.sql.ResultSet;
import java.sql.SQLException;
import conection.Consultas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luill
 */
public class frmFormularioCliente extends javax.swing.JDialog {

    /**
     * Creates new form frmFormularioCliente
     */
    public frmFormularioCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NewRegistro = new javax.swing.JButton();
        DeleteRegistro = new javax.swing.JButton();
        UpdateRegistro = new javax.swing.JButton();
        SelectRegistros = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Impresiones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNumCliente = new javax.swing.JTextField();
        TxtNomCliente = new javax.swing.JTextField();
        TxtCelCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(32767, 32767));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        NewRegistro.setText("Nuevo Registro");
        NewRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewRegistroActionPerformed(evt);
            }
        });

        DeleteRegistro.setText("Eliminar Registro");
        DeleteRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRegistroActionPerformed(evt);
            }
        });

        UpdateRegistro.setText("Actualizar Registro");
        UpdateRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRegistroActionPerformed(evt);
            }
        });

        SelectRegistros.setText("Consultar Datos");
        SelectRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectRegistrosActionPerformed(evt);
            }
        });

        Impresiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id_cliente", "nombre_cliente", "telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Impresiones);

        jLabel1.setText("número de cliente");

        jLabel2.setText("nombre del cliente");

        jLabel3.setText("teléfono del cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NewRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(TxtNumCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TxtNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TxtCelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(UpdateRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SelectRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewRegistro)
                    .addComponent(DeleteRegistro)
                    .addComponent(UpdateRegistro)
                    .addComponent(SelectRegistros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TxtNumCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TxtNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(TxtCelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewRegistroActionPerformed
   String idCliente = TxtNumCliente.getText().trim();
String nombreCliente = TxtNomCliente.getText().trim();
String telefono = TxtCelCliente.getText().trim();

// Verificar si todos los campos están llenos
if (!idCliente.isEmpty() && !nombreCliente.isEmpty() && !telefono.isEmpty()) {
    try {
        // Convertir el idCliente a entero
        int id = Integer.parseInt(idCliente);

        // Llamar al método insertarCliente con los datos proporcionados
        Consultas consultas = new Consultas();
        consultas.insertarCliente(nombreCliente, id, telefono);

        // Limpiar los campos de texto después de insertar el cliente
        TxtNumCliente.setText("");
        TxtNomCliente.setText("");
        TxtCelCliente.setText("");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID del cliente debe ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
    }
} else {
    JOptionPane.showMessageDialog(this, "Por favor, ingrese el ID, nombre y teléfono del cliente.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
}

 // TODO add your handling code here:
    // TODO add your handling code here:
    }//GEN-LAST:event_NewRegistroActionPerformed

    private void DeleteRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRegistroActionPerformed
   String idCliente = TxtNumCliente.getText().trim();
if (!idCliente.isEmpty()) {
    try {
        // Convertir el idCliente a entero
        int id = Integer.parseInt(idCliente);
        
        // Llamar al método borrarCliente con el ID proporcionado
        Consultas consultas = new Consultas();
        consultas.borrarCliente(id);
        
        // Limpiar el campo de ID después de borrar el cliente
        TxtNumCliente.setText("");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID del cliente debe ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
    }
} else {
    JOptionPane.showMessageDialog(this, "Por favor, ingrese el ID del cliente que desea borrar.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
}
// TODO add your handling code here:
    }//GEN-LAST:event_DeleteRegistroActionPerformed

    private void UpdateRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRegistroActionPerformed
    String idCliente = TxtNumCliente.getText().trim();
String nuevoNombreCliente = TxtNomCliente.getText().trim();
String nuevoTelefonoCliente = TxtCelCliente.getText().trim();

// Verificar si todos los campos están llenos
if (!idCliente.isEmpty() && !nuevoNombreCliente.isEmpty() && !nuevoTelefonoCliente.isEmpty()) {
    try {
        // Convertir el idCliente a entero
        int id = Integer.parseInt(idCliente);

        // Llamar al método actualizarCliente con los datos proporcionados
        Consultas consultas = new Consultas();
        consultas.actualizarCliente(id, nuevoNombreCliente, nuevoTelefonoCliente);

        // Limpiar los campos de texto después de actualizar el cliente
        TxtNumCliente.setText("");
        TxtNomCliente.setText("");
        TxtCelCliente.setText("");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID del cliente debe ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
    }
} else {
    JOptionPane.showMessageDialog(this, "Por favor, ingrese el ID, el nuevo nombre y el nuevo teléfono del cliente.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
}

  // TODO add your handling code here:
    }//GEN-LAST:event_UpdateRegistroActionPerformed

    private void SelectRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectRegistrosActionPerformed
 Consultas consultas = new Consultas();
ResultSet rs = consultas.consultarClientes();

DefaultTableModel modelo = new DefaultTableModel();
modelo.addColumn("ID cliente");
modelo.addColumn("Nombre cliente");
modelo.addColumn("Teléfono"); // Corrección en el nombre de la columna

// Verificar si se obtuvieron resultados
if (rs != null) {
    try {
        // Limpiar el modelo antes de agregar nuevos datos
        modelo.setRowCount(0);
        
        // Iterar sobre los resultados del ResultSet y agregarlos al modelo
        while (rs.next()) {
            int idCliente = rs.getInt("id_cliente");
            String nombreCliente = rs.getString("nombre_cliente");
            String telefono = rs.getString("telefono"); // Corrección en el tipo de dato obtenido
            
            // Agregar los datos al modelo
            modelo.addRow(new Object[]{idCliente, nombreCliente, telefono});
        }
        
        // Establecer el modelo en la tabla
        Impresiones.setModel(modelo);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al procesar los resultados de la consulta: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
} else {
    JOptionPane.showMessageDialog(this, "No se encontraron resultados.", "Información", JOptionPane.INFORMATION_MESSAGE);
}
 // TODO add your handling code here:
    }//GEN-LAST:event_SelectRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmFormularioCliente dialog = new frmFormularioCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteRegistro;
    private javax.swing.JTable Impresiones;
    private javax.swing.JButton NewRegistro;
    private javax.swing.JButton SelectRegistros;
    private javax.swing.JTextField TxtCelCliente;
    private javax.swing.JTextField TxtNomCliente;
    private javax.swing.JTextField TxtNumCliente;
    private javax.swing.JButton UpdateRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
